name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  equatable: ^2.0.5
  font_awesome_flutter: ^10.7.0
  go_router: ^17.0.0
  flutter_svg: ^2.2.2
  simple_gradient_text: ^1.3.0
  pin_code_fields: ^8.0.1
  stop_watch_timer: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Satoshi Variable
      fonts:
        - asset: assets/fonts/Satoshi-Variable.ttf
          weight: 700
    - family: Satoshi Regular
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 700
    - family: Satoshi Bold
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
    - family: Code Bold
      fonts:
        - asset: assets/fonts/CODE_Bold.otf
          weight: 700
    - family: Lato Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: DM SANS
      fonts:
        - asset: assets/fonts/DMSans_18pt-Regular.ttf
          weight: 500
    - family: DM SANS BOLD
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
    - family: Satoshi Black
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
    - family: SignUp
      fonts:
        - asset: assets/fonts/SignUp.ttf
    - family: BackArrow
      fonts:
        - asset: assets/fonts/back_arrow.ttf
    - family: ProfileIcon
      fonts:
        - asset: assets/fonts/profile_icon.ttf
    - family: IconsNavbar
      fonts:
        - asset: assets/fonts/Icons_navbar.ttf
    - family: CollectionIcons
      fonts:
        - asset: assets/fonts/Collection_Icons.ttf
    - family: VehicleArrow
      fonts:
        - asset: assets/fonts/vehicle_arrow.ttf
    - family: FinancialIcons
      fonts:
        - asset: assets/fonts/financial_icons.ttf
    - family: CalendarIco
      fonts:
        - asset: assets/fonts/calendar_ico.ttf
    - family: MaintenanceIcon
      fonts:
        - asset: assets/fonts/maintenance_icon.ttf
